language: cpp
sudo: false
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - gcc-snapshot
script:
  - CXX=/usr/lib/gcc-snapshot/bin/g++ LDFLAGS='-Wl,-R/usr/lib/gcc-snapshot/lib' cmake .
  - make all test
